### ISSUE TITLE
Don't suppose you could also add the class `autocomplete` to the prompt boxes it will let my browser highlight spelling mistakes like the usual prompt does

### ISSUE THREAD

**Issue by light-and-ray** [light-and-ray/sd-webui-replacer#66]
Don't suppose you could also add the class `autocomplete` to the prompt boxes it will let my browser highlight spelling mistakes like the usual prompt does

_Originally posted by @QuantumEntangledAndy in https://github.com/light-and-ray/sd-webui-replacer/issues/65#issuecomment-2068444642_

**Comment by QuantumEntangledAndy** [comment]
Hmm perhaps it was comming from one my extensions then, alright never mind then. I will see if I can work anything out on my end, (can close if you want)
